/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package org.xmlportletfactory.olafk.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Invoices service. Represents a row in the &quot;customer_Invoices&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.xmlportletfactory.olafk.customer.model.impl.InvoicesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.xmlportletfactory.olafk.customer.model.impl.InvoicesImpl}.
 * </p>
 *
 * @author Jack A. Rider
 * @see Invoices
 * @see org.xmlportletfactory.olafk.customer.model.impl.InvoicesImpl
 * @see org.xmlportletfactory.olafk.customer.model.impl.InvoicesModelImpl
 * @generated
 */
public interface InvoicesModel extends BaseModel<Invoices>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invoices model instance should use the {@link Invoices} interface instead.
	 */

	/**
	 * Returns the primary key of this invoices.
	 *
	 * @return the primary key of this invoices
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invoices.
	 *
	 * @param primaryKey the primary key of this invoices
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the invoice ID of this invoices.
	 *
	 * @return the invoice ID of this invoices
	 */
	public long getInvoiceId();

	/**
	 * Sets the invoice ID of this invoices.
	 *
	 * @param invoiceId the invoice ID of this invoices
	 */
	public void setInvoiceId(long invoiceId);

	/**
	 * Returns the company ID of this invoices.
	 *
	 * @return the company ID of this invoices
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this invoices.
	 *
	 * @param companyId the company ID of this invoices
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this invoices.
	 *
	 * @return the group ID of this invoices
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this invoices.
	 *
	 * @param groupId the group ID of this invoices
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this invoices.
	 *
	 * @return the user ID of this invoices
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this invoices.
	 *
	 * @param userId the user ID of this invoices
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this invoices.
	 *
	 * @return the user uuid of this invoices
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this invoices.
	 *
	 * @param userUuid the user uuid of this invoices
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this invoices.
	 *
	 * @return the user name of this invoices
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this invoices.
	 *
	 * @param userName the user name of this invoices
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this invoices.
	 *
	 * @return the create date of this invoices
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this invoices.
	 *
	 * @param createDate the create date of this invoices
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this invoices.
	 *
	 * @return the modified date of this invoices
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this invoices.
	 *
	 * @param modifiedDate the modified date of this invoices
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the customer ID of this invoices.
	 *
	 * @return the customer ID of this invoices
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this invoices.
	 *
	 * @param customerId the customer ID of this invoices
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the date of this invoices.
	 *
	 * @return the date of this invoices
	 */
	public Date getDate();

	/**
	 * Sets the date of this invoices.
	 *
	 * @param date the date of this invoices
	 */
	public void setDate(Date date);

	/**
	 * Returns the amount of this invoices.
	 *
	 * @return the amount of this invoices
	 */
	public long getAmount();

	/**
	 * Sets the amount of this invoices.
	 *
	 * @param amount the amount of this invoices
	 */
	public void setAmount(long amount);

	/**
	 * Returns the paid of this invoices.
	 *
	 * @return the paid of this invoices
	 */
	public boolean getPaid();

	/**
	 * Returns <code>true</code> if this invoices is paid.
	 *
	 * @return <code>true</code> if this invoices is paid; <code>false</code> otherwise
	 */
	public boolean isPaid();

	/**
	 * Sets whether this invoices is paid.
	 *
	 * @param paid the paid of this invoices
	 */
	public void setPaid(boolean paid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Invoices invoices);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Invoices> toCacheModel();

	@Override
	public Invoices toEscapedModel();

	@Override
	public Invoices toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}